name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  verify-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 18.17.0
          - 20.6.1
          - 21
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          cache: npm
          node-version: ${{ matrix.node }}
      - run: npm clean-install
      - run: npm audit signatures
      - run: npm test
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Setup node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm audit signatures
      - run: npm test
  release:
    needs:
      - verify
      - verify-matrix
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    uses: form8ion/.github/.github/workflows/release-package.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
permissions:
  contents: read
